version: '3.5'

services:
  paraview_dev:
    build: 
      context: .
      target: base
    volumes:
      - "./build:/app/paraview-build:rw"
      - "./VTK:/app/paraview-build/superbuild/paraview/src/VTK:ro"
      - "~/.Xauthority:/home/pvbuilder/.Xauthority:ro"
      - "./test:/app/test:rw"
      - "/:/host:ro"
    environment: 
      - DISPLAY=localhost:11.0
    ports:
      - "2000:2000"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: "${UID}:${GID}"
    network_mode: "host"

  paraview_release:
    build: 
      context: .
      target: release
    volumes:
      - "./release:/app/release:rw"
    entrypoint: "/bin/bash -c 'cp -f /app/*.tar.gz /app/release'"