version: '3.5'

services:
  paraview_debug:
    build: 
      context: .
      target: debug
      args:
        - GID=${UID}
        - UID=${UID}
    volumes:
      - "./build:/app/paraview-build:rw"
      - "./VTK:/app/paraview-build/superbuild/paraview/src/VTK:ro"
      - "~/.Xauthority:/home/pvbuilder/.Xauthority:ro"
      - "./test:/app/test:rw"
      - "/:/host:ro"
    environment: 
      - DISPLAY=localhost:11.0
    ports:
      - "2000:2000"
    user: "${UID}:${GID}"
    network_mode: "host"

  paraview_release:
    build: 
      context: .
      target: release
      args:
        - GID=${UID}
        - UID=${UID}
    volumes:
      - "./release:/app/release:rw"
    cap_add:
      - SYS_ADMIN
    devices: 
      - "/dev/fuse"
    security_opt: 
      - "apparmor:unconfined"
    user: "${UID}:${GID}"
